apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-dcc-api-depl
spec:
  replicas: 1                                   # number of pods
  selector:
    matchLabels:
      app: socket-dcc-api                       # looking for the pods name 'socket-dcc-api':
  template:
    metadata:
      labels:
        app: socket-dcc-api                     # our pod will have this label
    spec:
      containers:
        - name: socket-dcc-api
          image: socket-api/node:0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: socket-api-srv
spec:
  selector:
    app: socket-api
  type: NodePort
  ports:
    - name: socket-api
      protocol: TCP
      port: 3000
      targetPort: 3000
